### PR TITLE
Navbar and transition to scss

### LINKED ISSUE #20: Create floating navbar
- Please refer to the [design](https://www.figma.com/file/Ig70QETLgR6Y0ZPj8ZJuTr/KOSS-Website-(Astro)?type=design&node-id=0-1&mode=design&t=Rf7FMFZJfeXlOp5P-0).
- Create a navbar component [here](https://github.com/kossiitkgp/YAKW/tree/master/src/components).
- Use the component [here](https://github.com/kossiitkgp/YAKW/blob/master/src/layouts/Layout.astro).

image

### PR DESCRIPTION
**Pull request by chirag-ghosh**
- closes #20 
- using scss for styling (since Astro styles are [scoped](https://docs.astro.build/en/guides/styling/#scoped-styles), I think scss should be a good addition)

### CODE REVIEW

**Comment by rohan-b-84** [comment]
What resolution are we building this site in ?

My Resolution is 1368*768
This is how it looks in my PC
image

**Comment by rajivharlalka** [comment]
[image: image.png]

Looks fine for me

Regards,
Rajiv Harlalka,
Department of Mathematics
20MA20073,
Phone: +918987966604
Indian Institute of Technology, Kharagpur

**Comment by proffapt** [comment]
image

IDK much design but, doesn't it look too much bulky? (height wise..)

**Comment by chirag-ghosh** [comment]
Let's discuss this in slack @rohan-b-84 @proffapt

**Review by harshkhandeparkar — APPROVED** [review]

**Review by rajivharlalka — APPROVED** [review]
LGTM :)

**Comment by rajivharlalka** [comment]
Also would recommened different PR for different features, would be eadier to review stuff.

**Pull request merged**
